CREATE DATABASE rehabilitacion_fisica;
\c rehabilitacion_fisica;
 
 
-- ============================================================
-- CATÁLOGOS DE DOMINIO
-- ============================================================
 
CREATE TABLE cat_sexo (
    id_sexo  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre   VARCHAR(20) NOT NULL UNIQUE,   -- MASCULINO | FEMENINO | OTRO
    activo   BOOLEAN NOT NULL DEFAULT TRUE
);
 
CREATE TABLE cat_especialidades (
    id_especialidad  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR(100) NOT NULL UNIQUE,
    activo           BOOLEAN NOT NULL DEFAULT TRUE
);
 
CREATE TABLE cat_tipos_sesion (
    id_tipo_sesion  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(30) NOT NULL UNIQUE,  -- Individual | Grupal | Respiratoria
    activo          BOOLEAN NOT NULL DEFAULT TRUE
);
 
CREATE TABLE cat_metodos_registro (
    id_metodo  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre     VARCHAR(20) NOT NULL UNIQUE,       -- NFC | Manual
    activo     BOOLEAN NOT NULL DEFAULT TRUE
);
 
CREATE TABLE cat_tipos_ejercicio (
    id_tipo_ejercicio  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre             VARCHAR(50) NOT NULL UNIQUE,
    activo             BOOLEAN NOT NULL DEFAULT TRUE
);
 
CREATE TABLE cat_nivel_dificultad (
    id_nivel  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    CHAR(5) NOT NULL UNIQUE,            -- BAJO | MEDIO | ALTO
    activo    BOOLEAN NOT NULL DEFAULT TRUE
);
 
CREATE TABLE cat_estados_dispositivo (
    id_estado  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre     VARCHAR(20) NOT NULL UNIQUE,       -- ACTIVO | INACTIVO | MANTENIMIENTO
    activo     BOOLEAN NOT NULL DEFAULT TRUE
);
 
CREATE TABLE cat_estados_beacon (
    id_estado  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre     CHAR(8) NOT NULL UNIQUE,           -- ACTIVO | INACTIVO
    activo     BOOLEAN NOT NULL DEFAULT TRUE
);
 
CREATE TABLE cat_estados_gps (
    id_estado  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre     CHAR(10) NOT NULL UNIQUE,          -- EN_RUTA | LLEGADO | FINALIZADO
    activo     BOOLEAN NOT NULL DEFAULT TRUE
);
 
CREATE TABLE cat_estados_vehiculo (
    id_estado  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre     CHAR(12) NOT NULL UNIQUE,          -- DISPONIBLE | EN_USO | MANTENIMIENTO
    activo     BOOLEAN NOT NULL DEFAULT TRUE
);
 
 
-- ============================================================
-- ENTIDADES MAESTRAS
-- ============================================================
 
CREATE TABLE pacientes (
    id_paciente           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                VARCHAR(50)  NOT NULL,
    apellido_paterno      VARCHAR(50)  NOT NULL,
    apellido_materno      VARCHAR(50)  NOT NULL,
    fecha_nacimiento      DATE         NOT NULL,
    id_sexo               INTEGER      NOT NULL,
    telefono              VARCHAR(15),
    correo                VARCHAR(100) UNIQUE,
    direccion             VARCHAR(150),
    diagnostico_principal VARCHAR(100) NOT NULL,
    antecedentes_medicos  TEXT,
    FOREIGN KEY (id_sexo) REFERENCES cat_sexo(id_sexo)
        ON DELETE RESTRICT ON UPDATE CASCADE
);
 
CREATE TABLE terapeutas (
    id_terapeuta      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            VARCHAR(50)  NOT NULL,
    apellido_paterno  VARCHAR(50)  NOT NULL,
    apellido_materno  VARCHAR(50)  NOT NULL,
    id_sexo           INTEGER      NOT NULL,
    id_especialidad   INTEGER      NOT NULL,
    telefono          VARCHAR(15),
    correo            VARCHAR(100) UNIQUE,
    observaciones     TEXT,
    FOREIGN KEY (id_especialidad) REFERENCES cat_especialidades(id_especialidad)
        ON DELETE RESTRICT ON UPDATE CASCADE
    FOREIGN KEY (id_sexo) REFERENCES cat_sexo(id_sexo)
        ON DELETE RESTRICT ON UPDATE CASCADE
);
 
CREATE TABLE ejercicios (
    id_ejercicio        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_ejercicio    VARCHAR(100) NOT NULL,
    descripcion         TEXT         NOT NULL,
    id_tipo_ejercicio   INTEGER      NOT NULL,
    id_nivel_dificultad INTEGER      NOT NULL,
    FOREIGN KEY (id_tipo_ejercicio)   REFERENCES cat_tipos_ejercicio(id_tipo_ejercicio)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (id_nivel_dificultad) REFERENCES cat_nivel_dificultad(id_nivel)
        ON DELETE RESTRICT ON UPDATE CASCADE
);
 
CREATE TABLE vehiculos (
    id_vehiculo  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo         VARCHAR(50) NOT NULL,
    descripcion  TEXT        NOT NULL,
    id_estado    INTEGER     NOT NULL,
    FOREIGN KEY (id_estado) REFERENCES cat_estados_vehiculo(id_estado)
        ON DELETE RESTRICT ON UPDATE CASCADE
);
 
CREATE TABLE dispositivos_nfc (
    id_dispositivo   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_dispositivo VARCHAR(50)  NOT NULL,
    ubicacion        VARCHAR(100) NOT NULL,
    id_estado        INTEGER      NOT NULL,
    descripcion      TEXT,
    FOREIGN KEY (id_estado) REFERENCES cat_estados_dispositivo(id_estado)
        ON DELETE RESTRICT ON UPDATE CASCADE
);
 
CREATE TABLE beacons (
    id_beacon   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area        VARCHAR(50) NOT NULL,
    habitacion  VARCHAR(50) NOT NULL,
    id_estado   INTEGER     NOT NULL,
    FOREIGN KEY (id_estado) REFERENCES cat_estados_beacon(id_estado)
        ON DELETE RESTRICT ON UPDATE CASCADE
);
 
 
-- ============================================================
-- AUTENTICACIÓN
-- ============================================================
 
CREATE TABLE usuarios (
    id_usuario   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login        VARCHAR(30)  NOT NULL UNIQUE,
    password     VARCHAR(256) NOT NULL,
    rol          VARCHAR(20)  NOT NULL
                   CHECK (rol IN ('admin', 'terapeuta', 'familiar')),
    ref_id       INTEGER,                         -- id_paciente o id_terapeuta según rol
    activo       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
 
 
-- ============================================================
-- ENTIDADES TRANSACCIONALES
-- ============================================================
 
CREATE TABLE sesiones (
    id_sesion              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha                  DATE        NOT NULL,
    hora_inicio            TIME        NOT NULL,
    hora_fin               TIME        NOT NULL,
    id_tipo_sesion         INTEGER     NOT NULL,
    observaciones_clinicas TEXT,
    asistencia             BOOLEAN     NOT NULL DEFAULT FALSE,
    id_metodo              INTEGER     NOT NULL,
    -- Columnas para tracking en tiempo real
    hora_inicio_real       TIMESTAMP,
    hora_fin_real          TIMESTAMP,
    estado_sesion          VARCHAR(20) NOT NULL DEFAULT 'PROGRAMADA'
                             CHECK (estado_sesion IN ('PROGRAMADA','EN_CURSO','FINALIZADA','CANCELADA')),
    CONSTRAINT check_horas CHECK (hora_fin > hora_inicio),
    FOREIGN KEY (id_tipo_sesion) REFERENCES cat_tipos_sesion(id_tipo_sesion)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (id_metodo)      REFERENCES cat_metodos_registro(id_metodo)
        ON DELETE RESTRICT ON UPDATE CASCADE
);
 
CREATE TABLE evaluaciones_progreso (
    id_evaluacion      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha              DATE         NOT NULL,
    tipo_evaluacion    VARCHAR(50)  NOT NULL,
    nivel_movilidad    SMALLINT     NOT NULL CHECK (nivel_movilidad BETWEEN 0 AND 10),
    nivel_dolor        SMALLINT     NOT NULL CHECK (nivel_dolor     BETWEEN 0 AND 10),
    resistencia        SMALLINT     NOT NULL CHECK (resistencia     BETWEEN 0 AND 10),
    progreso_observado TEXT,
    recomendaciones    TEXT,
    ajustes_plan       TEXT
);
 
 
-- ============================================================
-- TABLAS MULTIVALUADAS
-- ============================================================
 
CREATE TABLE paciente_alergia (
    id_paciente  INTEGER      NOT NULL,
    alergia      VARCHAR(100) NOT NULL,
    PRIMARY KEY (id_paciente, alergia),
    FOREIGN KEY (id_paciente) REFERENCES pacientes(id_paciente)
        ON DELETE CASCADE ON UPDATE CASCADE
);
 
CREATE TABLE paciente_lesion (
    id_paciente   INTEGER      NOT NULL,
    lesion_previa VARCHAR(100) NOT NULL,
    PRIMARY KEY (id_paciente, lesion_previa),
    FOREIGN KEY (id_paciente) REFERENCES pacientes(id_paciente)
        ON DELETE CASCADE ON UPDATE CASCADE
);
 
CREATE TABLE paciente_medicamento (
    id_paciente        INTEGER      NOT NULL,
    medicamento_actual VARCHAR(100) NOT NULL,
    PRIMARY KEY (id_paciente, medicamento_actual),
    FOREIGN KEY (id_paciente) REFERENCES pacientes(id_paciente)
        ON DELETE CASCADE ON UPDATE CASCADE
);
 
 
-- ============================================================
-- RELACIONES N:M
-- ============================================================
 
CREATE TABLE paciente_terapeuta (
    id_paciente  INTEGER NOT NULL,
    id_terapeuta INTEGER NOT NULL,
    PRIMARY KEY (id_paciente, id_terapeuta),
    FOREIGN KEY (id_paciente)  REFERENCES pacientes(id_paciente)
        ON DELETE CASCADE  ON UPDATE CASCADE,
    FOREIGN KEY (id_terapeuta) REFERENCES terapeutas(id_terapeuta)
        ON DELETE RESTRICT ON UPDATE CASCADE
);
 
CREATE TABLE paciente_sesion (
    id_paciente INTEGER NOT NULL,
    id_sesion   INTEGER NOT NULL,
    PRIMARY KEY (id_paciente, id_sesion),
    FOREIGN KEY (id_paciente) REFERENCES pacientes(id_paciente)
        ON DELETE CASCADE  ON UPDATE CASCADE,
    FOREIGN KEY (id_sesion)   REFERENCES sesiones(id_sesion)
        ON DELETE CASCADE  ON UPDATE CASCADE
);
 
CREATE TABLE terapeuta_sesion (
    id_terapeuta INTEGER NOT NULL,
    id_sesion    INTEGER NOT NULL,
    PRIMARY KEY (id_terapeuta, id_sesion),
    FOREIGN KEY (id_terapeuta) REFERENCES terapeutas(id_terapeuta)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (id_sesion)    REFERENCES sesiones(id_sesion)
        ON DELETE CASCADE  ON UPDATE CASCADE
);
 
CREATE TABLE paciente_evaluacion (
    id_paciente   INTEGER NOT NULL,
    id_evaluacion INTEGER NOT NULL,
    PRIMARY KEY (id_paciente, id_evaluacion),
    FOREIGN KEY (id_paciente)   REFERENCES pacientes(id_paciente)
        ON DELETE CASCADE  ON UPDATE CASCADE,
    FOREIGN KEY (id_evaluacion) REFERENCES evaluaciones_progreso(id_evaluacion)
        ON DELETE CASCADE  ON UPDATE CASCADE
);
 
CREATE TABLE evaluacion_terapeuta (
    id_evaluacion INTEGER NOT NULL,
    id_terapeuta  INTEGER NOT NULL,
    PRIMARY KEY (id_evaluacion, id_terapeuta),
    FOREIGN KEY (id_evaluacion) REFERENCES evaluaciones_progreso(id_evaluacion)
        ON DELETE CASCADE  ON UPDATE CASCADE,
    FOREIGN KEY (id_terapeuta)  REFERENCES terapeutas(id_terapeuta)
        ON DELETE RESTRICT ON UPDATE CASCADE
);
 
CREATE TABLE ejercicio_sesion_detalle (
    id_sesion    INTEGER  NOT NULL,
    id_ejercicio INTEGER  NOT NULL,
    repeticiones SMALLINT NOT NULL CHECK (repeticiones > 0),
    duracion_min SMALLINT NOT NULL CHECK (duracion_min > 0),
    observaciones TEXT,
    PRIMARY KEY (id_sesion, id_ejercicio),
    FOREIGN KEY (id_sesion)    REFERENCES sesiones(id_sesion)
        ON DELETE CASCADE  ON UPDATE CASCADE,
    FOREIGN KEY (id_ejercicio) REFERENCES ejercicios(id_ejercicio)
        ON DELETE RESTRICT ON UPDATE CASCADE
);
 
 
-- ============================================================
-- IoT — EVENTOS
-- ============================================================
 
CREATE TABLE asistencias_nfc (
    id_asistencia         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente           INTEGER NOT NULL,
    id_sesion             INTEGER NOT NULL,
    fecha                 DATE    NOT NULL,
    hora_entrada          TIME    NOT NULL,
    asistencia_confirmada BOOLEAN NOT NULL,
    id_dispositivo        INTEGER NOT NULL,
    CONSTRAINT uq_asistencia_paciente_sesion UNIQUE (id_paciente, id_sesion),
    FOREIGN KEY (id_paciente)    REFERENCES pacientes(id_paciente)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (id_sesion)      REFERENCES sesiones(id_sesion)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (id_dispositivo) REFERENCES dispositivos_nfc(id_dispositivo)
        ON DELETE RESTRICT ON UPDATE CASCADE
);
 
CREATE TABLE beacon_evento (
    id_evento   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_beacon   INTEGER NOT NULL,
    id_paciente INTEGER NOT NULL,
    fecha       DATE    NOT NULL,
    hora        TIME    NOT NULL,
    FOREIGN KEY (id_beacon)   REFERENCES beacons(id_beacon)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (id_paciente) REFERENCES pacientes(id_paciente)
        ON DELETE RESTRICT ON UPDATE CASCADE
);
 
CREATE TABLE gps_registros (
    id_registro  INTEGER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente  INTEGER        NOT NULL,
    id_terapeuta INTEGER        NOT NULL,
    latitud      NUMERIC(8,6)   NOT NULL CHECK (latitud  BETWEEN -90  AND 90),
    longitud     NUMERIC(9,6)   NOT NULL CHECK (longitud BETWEEN -180 AND 180),
    fecha        DATE           NOT NULL,
    hora         TIME           NOT NULL,
    id_estado    INTEGER        NOT NULL,
    FOREIGN KEY (id_paciente)  REFERENCES pacientes(id_paciente)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (id_terapeuta) REFERENCES terapeutas(id_terapeuta)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (id_estado)    REFERENCES cat_estados_gps(id_estado)
        ON DELETE RESTRICT ON UPDATE CASCADE
);
 
CREATE TABLE gps_vehiculo (
    id_registro INTEGER NOT NULL,
    id_vehiculo INTEGER NOT NULL,
    PRIMARY KEY (id_registro, id_vehiculo),
    FOREIGN KEY (id_registro) REFERENCES gps_registros(id_registro)
        ON DELETE CASCADE  ON UPDATE CASCADE,
    FOREIGN KEY (id_vehiculo) REFERENCES vehiculos(id_vehiculo)
        ON DELETE RESTRICT ON UPDATE CASCADE
);
 
-- ============================================================
-- NFC — VINCULACIÓN TARJETA ↔ PACIENTE
-- ============================================================
 
CREATE TABLE nfc_uids (
    id_nfc      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_paciente INTEGER      NOT NULL,
    uid         VARCHAR(50)  NOT NULL UNIQUE,
    activo      BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_asig  DATE         NOT NULL DEFAULT CURRENT_DATE,
    FOREIGN KEY (id_paciente) REFERENCES pacientes(id_paciente)
        ON DELETE CASCADE ON UPDATE CASCADE
);
 
 
-- ============================================================
-- ÍNDICES ESTRATÉGICOS
-- ============================================================
 
CREATE INDEX idx_asistencia_paciente  ON asistencias_nfc(id_paciente);
CREATE INDEX idx_asistencia_sesion    ON asistencias_nfc(id_sesion);
CREATE INDEX idx_sesiones_fecha       ON sesiones(fecha DESC);
CREATE INDEX idx_sesiones_estado      ON sesiones(estado_sesion);
CREATE INDEX idx_gps_fecha            ON gps_registros(fecha DESC);
CREATE INDEX idx_gps_paciente         ON gps_registros(id_paciente);
CREATE INDEX idx_beacon_paciente      ON beacon_evento(id_paciente);
CREATE INDEX idx_beacon_fecha         ON beacon_evento(fecha DESC);
CREATE INDEX idx_evaluaciones_fecha   ON evaluaciones_progreso(fecha DESC);
CREATE INDEX idx_esd_sesion           ON ejercicio_sesion_detalle(id_sesion);
CREATE INDEX idx_nfc_uid              ON nfc_uids(uid);
CREATE INDEX idx_usuarios_login       ON usuarios(login);
